---
- name: run apache
  become: yes
  hosts: apache
  tasks:
    - name: Install apache2 server
      ansible.builtin.apt:
        name:
          - apache2
        state: present
        update_cache: yes