---
- name: run apache
  become: yes
  hosts: 172.31.43.40
  tasks:
    - name: Install apache2 server
      ansible.builtin.apt:
        name: 
          - apache2
        state: present
        update_cache: yes