---
- name: Run PHP on RedHat (Apache)
  become: yes
  hosts: redhat
  tasks:
    - name: Install php on redhat
      ansible.builtin.yum:
        name: 
          - httpd
          - php
          - php-cli
          - php-common
          - php-gd
          - php-mysqlnd
          - php-pdo
        state: prestnt
    - name: create info.php
      ansible.builtin.file:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
    - name: httpd service run
      ansible.builtin.service:
        name: httpd
        state: staretd
        enabled: yes
