---
- name: Install php on redhat
  become: yes
  hosts: 172.31.32.113
  tasks:
    - name: install apache
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-cli
          - php-common
        state: latest
    - name: create a file
      ansible.builtin.file:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
    # - name: httpd service run
    #   ansible.builtin.service:
    #     name: httpd
    #     state: staretd
    #     enabled: yes
